---
# This playbook remove a webserver from the load balancer

- hosts: haproxy
  tasks:
    - name: Temporary removing the host {{ targethost }} from Loadbalancer
      replace:
        dest: /etc/haproxy/haproxy.cfg
        regexp: 'server {{ targethost }}'
        replace: '#server {{ targethost }}'
        backup: yes

  handlers:
    - name: reload haproxy
      service: name=haproxy state=reloaded
