---
# This playbook remove a webserver from the load balancer

- hosts: haproxy
  tasks:
    - name: Temporary removing the host {{ targethost }} from Loadbalancer
      haproxy: 'state=disabled backend=myloadbalancer host={{ targethost }} socket=/var/lib/haproxy/stats'

# Dirty & old way
#    - name: Temporary removing the host {{ targethost }} from Loadbalancer
#      replace:
#        dest: /etc/haproxy/haproxy.cfg
#        regexp: 'server {{ targethost }}'
#        replace: '#server {{ targethost }}'
#        backup: yes
#      notify: reload haproxy
#
#  handlers:
#    - name: reload haproxy
#      service: name=haproxy state=reloaded
