---
# This playbook re-add a webserver to the load balancer

- hosts: haproxy
  tasks:
    - name: Reinserting the host {{ targethost }} into Loadbalancer
      haproxy: 'state=enabled backend=myloadbalancer host={{ targethost }} socket=/var/lib/haproxy/stats'

